"""Mock data fixtures for testing NLB Intelligence modules."""

from src.models import (
    TitleSearchResult, TitleDetail, ItemAvailability, LibraryBranch,
    CheckoutTrend, Recommendation, EResource,
)

MOCK_LIBRARIES = [
    LibraryBranch(
        code="TRL", name="Tampines Regional Library",
        address="1 Tampines Walk", postal_code="529684",
        telephone="6788 8828", latitude=1.352, longitude=103.945,
        weekday_hours="10:00am - 9:00pm",
        saturday_hours="10:00am - 9:00pm",
        sunday_hours="10:00am - 9:00pm",
        has_event_space=True, has_meeting_room=True,
    ),
    LibraryBranch(
        code="WRL", name="Woodlands Regional Library",
        address="900 S Woodlands Dr", postal_code="730900",
        telephone="6778 8828", latitude=1.436, longitude=103.786,
        weekday_hours="10:00am - 9:00pm",
        saturday_hours="10:00am - 9:00pm",
        sunday_hours="11:00am - 9:00pm",
        has_event_space=True, has_meeting_room=True,
    ),
    LibraryBranch(
        code="CEN", name="Central Arts Library",
        address="100 Victoria Street", postal_code="188064",
        telephone="6332 3255", latitude=1.297, longitude=103.853,
        weekday_hours="10:00am - 9:00pm",
        saturday_hours="10:00am - 9:00pm",
        sunday_hours="11:00am - 6:00pm",
        has_event_space=True, has_meeting_room=False,
    ),
    LibraryBranch(
        code="JRL", name="Jurong Regional Library",
        address="21 Jurong East Central 1", postal_code="609732",
        telephone="6778 8828", latitude=1.332, longitude=103.742,
        weekday_hours="10:00am - 9:00pm",
        saturday_hours="10:00am - 9:00pm",
        sunday_hours="10:00am - 9:00pm",
        has_event_space=True, has_meeting_room=True,
    ),
    LibraryBranch(
        code="SKG", name="Sengkang Public Library",
        address="1 Sengkang Square", postal_code="545078",
        telephone="6880 8828", latitude=1.391, longitude=103.895,
        weekday_hours="10:00am - 9:00pm",
        saturday_hours="10:00am - 9:00pm",
        sunday_hours="10:00am - 9:00pm",
        has_event_space=False, has_meeting_room=True,
    ),
]

MOCK_SEARCH_RESULTS = [
    TitleSearchResult(
        brn="BRN123456", title="Singapore: A Biography",
        author="Mark Frost", isbn="9789811234567",
        format="BOOK", publisher="NUS Press",
        publish_date="2020", language="English",
        subjects=["Singapore", "History", "Biography"],
        book_cover="https://example.com/cover1.jpg",
        availability="On Shelf",
    ),
    TitleSearchResult(
        brn="BRN789012", title="The Art of Charlie Chan Hock Chye",
        author="Sonny Liew", isbn="9789817890123",
        format="BOOK", publisher="Epigram Books",
        publish_date="2015", language="English",
        subjects=["Comics", "Singapore", "History", "Art"],
        book_cover="https://example.com/cover2.jpg",
        availability="On Loan",
    ),
    TitleSearchResult(
        brn="BRN345678", title="From Third World to First",
        author="Lee Kuan Yew", isbn="9789813456789",
        format="BOOK", publisher="Straits Times Press",
        publish_date="2000", language="English",
        subjects=["Singapore", "Politics", "Economics", "History"],
        book_cover="https://example.com/cover3.jpg",
        availability="On Shelf",
    ),
    TitleSearchResult(
        brn="BRN901234", title="Sejarah Melayu",
        author="Tun Sri Lanang", isbn="9789819012345",
        format="BOOK", publisher="Malay Heritage Centre",
        publish_date="1998", language="Malay",
        subjects=["Malay Literature", "History", "Southeast Asia"],
        book_cover="https://example.com/cover4.jpg",
        availability="Available",
    ),
    TitleSearchResult(
        brn="BRN567890", title="Singapore Hawker Heritage",
        author="KF Seetoh", isbn="9789815678901",
        format="BOOK", publisher="Marshall Cavendish",
        publish_date="2019", language="English",
        subjects=["Cooking", "Singapore", "Heritage", "Food"],
        book_cover="https://example.com/cover5.jpg",
        availability="On Shelf",
    ),
    TitleSearchResult(
        brn="BRN112233", title="Tamil Poetry of Singapore",
        author="R. K. Nathan", isbn="9789811122336",
        format="BOOK", publisher="Tamil Literature Society",
        publish_date="2005", language="Tamil",
        subjects=["Tamil Literature", "Poetry", "Singapore"],
        book_cover="https://example.com/cover6.jpg",
        availability="On Shelf",
    ),
    TitleSearchResult(
        brn="BRN445566", title="Artificial Intelligence: A Modern Approach",
        author="Stuart Russell", isbn="9789814455667",
        format="BOOK", publisher="Pearson",
        publish_date="2020", language="English",
        subjects=["Artificial Intelligence", "Computer Science", "Technology"],
        book_cover="https://example.com/cover7.jpg",
        availability="On Shelf",
    ),
]

MOCK_TITLE_DETAILS = TitleDetail(
    brn="BRN123456",
    title="Singapore: A Biography",
    authors=["Mark Frost", "Yu-Mei Balasingamchow"],
    isbns=["9789811234567", "9789811234568"],
    format="BOOK",
    edition="Hardcover",
    publisher="NUS Press",
    publish_date="2020",
    subjects=["Singapore", "History", "Biography", "Southeast Asia"],
    summary="A comprehensive biographical history of Singapore from its founding as a British colony to the present day.",
    language="English",
    audience="adult",
    physical_description="456 pages : illustrations ; 24 cm",
    book_cover_small="https://example.com/small1.jpg",
    book_cover_medium="https://example.com/medium1.jpg",
    book_cover_large="https://example.com/large1.jpg",
    allow_reservation=True,
    is_restricted=False,
    active_reservations_count=8,
)

MOCK_AVAILABILITY = [
    ItemAvailability(
        branch_code="TRL", branch_name="Tampines Regional Library",
        shelf_location="Adult Lending", call_number="SIN 959.57 FRO",
        status_code="AVAILABLE", status_desc="On Shelf", collection="Adult Lending",
    ),
    ItemAvailability(
        branch_code="CEN", branch_name="Central Arts Library",
        shelf_location="Singapore Collection", call_number="SIN 959.57 FRO",
        status_code="ON_LOAN", status_desc="On Loan", collection="Singapore Collection",
    ),
    ItemAvailability(
        branch_code="SKG", branch_name="Sengkang Public Library",
        shelf_location="Adult Lending", call_number="SIN 959.57 FRO",
        status_code="AVAILABLE", status_desc="On Shelf", collection="Adult Lending",
    ),
]

MOCK_CHECKOUT_TRENDS = [
    CheckoutTrend(brn="BRN123456", title="Singapore: A Biography",
                   checkout_count=45, branch_code="TRL",
                   branch_name="Tampines Regional Library", period="past30days"),
    CheckoutTrend(brn="BRN789012", title="The Art of Charlie Chan Hock Chye",
                   checkout_count=38, branch_code="TRL",
                   branch_name="Tampines Regional Library", period="past30days"),
    CheckoutTrend(brn="BRN345678", title="From Third World to First",
                   checkout_count=52, branch_code="TRL",
                   branch_name="Tampines Regional Library", period="past30days"),
    CheckoutTrend(brn="BRN567890", title="Singapore Hawker Heritage",
                   checkout_count=29, branch_code="TRL",
                   branch_name="Tampines Regional Library", period="past30days"),
    CheckoutTrend(brn="BRN901234", title="Sejarah Melayu",
                   checkout_count=15, branch_code="CEN",
                   branch_name="Central Arts Library", period="past30days"),
    CheckoutTrend(brn="BRN112233", title="Tamil Poetry of Singapore",
                   checkout_count=12, branch_code="CEN",
                   branch_name="Central Arts Library", period="past30days"),
    CheckoutTrend(brn="BRN345678", title="From Third World to First",
                   checkout_count=48, branch_code="WRL",
                   branch_name="Woodlands Regional Library", period="past30days"),
    CheckoutTrend(brn="BRN123456", title="Singapore: A Biography",
                   checkout_count=33, branch_code="WRL",
                   branch_name="Woodlands Regional Library", period="past30days"),
]

MOCK_RECOMMENDATIONS = [
    Recommendation(brn="BRN789012", title="The Art of Charlie Chan Hock Chye",
                   author="Sonny Liew", isbn="9789817890123",
                   category="Comics & Graphic Novels", book_cover=""),
    Recommendation(brn="BRN567890", title="Singapore Hawker Heritage",
                   author="KF Seetoh", isbn="9789815678901",
                   category="Cooking & Food", book_cover=""),
    Recommendation(brn="BRN901234", title="Sejarah Melayu",
                   author="Tun Sri Lanang", isbn="9789819012345",
                   category="History", book_cover=""),
]

MOCK_ERESOURCES = [
    EResource(
        title="Singapore History Online",
        content_type="ebooks",
        summary="A comprehensive digital collection of Singapore historical texts",
        creator="National Library Board",
        subject="History",
        source="NLB",
        url="https://eresources.nlb.gov.sg/history",
        date="2024",
    ),
    EResource(
        title="Malay Heritage Digital Archive",
        content_type="images",
        summary="Digitised photographs of Malay heritage in Singapore",
        creator="National Archives of Singapore",
        subject="Heritage",
        source="NAS",
        url="https://eresources.nlb.gov.sg/malay",
        date="2023",
    ),
]
